local TestEnv = require("ApiKitTestEnv")

describe("ApiKit short global", function()
    after_each(TestEnv.Reset)

    it("publishes wow when nothing owns the name", function()
        local ApiKit = TestEnv.NewPackageFor("retail")
        assert.are.equal("published", ApiKit:GetGlobalStatus())
        -- selene: allow(global_usage)
        assert.are.equal(rawget(_G, "MoltenCodes").wow, rawget(_G, "wow"))
    end)

    it("leaves a taken wow alone and says so", function()
        TestEnv.Reset()
        TestEnv.InstallWowApi()
        TestEnv.SetClient({ projectId = 1, testBuild = false, betaBuild = false })
        local other = { belongsTo = "another addon" }
        -- selene: allow(global_usage)
        rawset(_G, "wow", other)
        require("Registry")
        local ApiKit = require("ApiKit")

        assert.are.equal("taken", ApiKit:GetGlobalStatus())
        -- selene: allow(global_usage)
        assert.are.equal(other, rawget(_G, "wow"))
        -- selene: allow(global_usage)
        assert.is_table(rawget(_G, "MoltenCodes").wow.retail.api)
    end)

    it("keeps its status across a reload", function()
        local ApiKit = TestEnv.NewPackageFor("retail")
        TestEnv.ReloadPackage()
        assert.are.equal("published", ApiKit:GetGlobalStatus())
        -- selene: allow(global_usage)
        assert.are.equal(rawget(_G, "MoltenCodes").wow, rawget(_G, "wow"))
    end)

    it("never reclaims wow after another addon replaced it, and says so", function()
        local ApiKit = TestEnv.NewPackageFor("retail")
        local other = {}
        -- selene: allow(global_usage)
        rawset(_G, "wow", other)
        TestEnv.ReloadPackage()
        -- selene: allow(global_usage)
        assert.are.equal(other, rawget(_G, "wow"))
        -- The status is read live, so the replacement is reported.
        assert.are.equal("taken", ApiKit:GetGlobalStatus())
    end)

    it("refuses a MoltenCodes.wow owned by something else", function()
        TestEnv.Reset()
        TestEnv.InstallWowApi()
        TestEnv.SetClient({ projectId = 1, testBuild = false, betaBuild = false })
        require("Registry")
        -- selene: allow(global_usage)
        rawset(rawget(_G, "MoltenCodes"), "wow", { foreign = true })
        TestEnv.expectErrorContaining("MoltenCodes.wow owned by something else", function()
            TestEnv.requireAfterFailedLoad("ApiKit")
        end)
    end)
end)
