"""Render one flavour's LuaCATS definitions: the types an editor completes against.

`docs/API_KIT_DESIGN.md` (section 10) promises that `local api = wow.retail.api`
completes to exactly what Retail has and `local api = wow.classic.era.api` to
exactly what Classic Era has. This module writes the definition files that
make lua-language-server keep that promise, for one flavour, from the
flavour's metadata (`tooling.api.model`). The files land in
`packages/apiKit/types/<flavour id>/` and are development files: every one
starts with `---@meta`, and the client never loads them.

The set of files, each owning one part of the surface:

- `api.lua`: the `wow` global, the flavour path (`wow.retail`) and the `api`
  class, with one class per namespace and a stub per function;
- `events.lua`: `<ns>.events` (wrapper name to event string) and
  `<ns>.eventPayloads` (event string to handler signature);
- `enums.lua`: the `Enum` global with one `---@enum` table per enumeration,
  and `<ns>.enums`;
- `structures.lua`: one class per structure, one `---@alias` per callback;
- `constants.lua`: the `Constants` global with one class per constants table,
  and `<ns>.constants`;
- `objects.lua`: one class per script object type, with its methods;
- `host.lua`: the host types from `types.json`, as aliases and empty classes.

Choices worth knowing:

- Namespaces are declared as fields of a single `local api = {}` table
  (`api.timer = {}`) rather than one local per namespace: Lua allows 200
  locals per chunk and Retail has more namespaces than that. Object types
  keep the one-local-per-class form of the repository's hand-written meta
  files because they are far fewer and methods read best as `Class:Method`.
- Documentation goes on `---` lines above the annotation they describe,
  wrapped at `DOC_COLUMN_WIDTH`, never appended to an `---@field` or
  `---@param` line: a signature cannot be wrapped, so prose is kept off it.
- A parameter named after a Lua keyword (`end`, `function`) is written with a
  trailing underscore. The names are only there for hover text; the types and
  positions are what matter.
- The output is deterministic and already in the shape StyLua produces for the
  repository's configuration, so the formatter is a check rather than a step.
"""

from __future__ import annotations

import dataclasses
import textwrap
from typing import Iterable, Sequence

from tooling.api import flavours, model


#: The first lines of every generated definition file, as `str.format`
#: templates over the flavour's provenance (see `header_lines`). The
#: `---@meta` line must stay first: it is what marks the file as definitions
#: only, never code the language server expects the workspace to run.
GENERATED_HEADER_LINES: tuple[str, ...] = (
    "---@meta",
    "-- Generated by `python3 -m tooling.api.generate` from the {flavour} metadata.",
    "-- Source: {repository}, client {version} build {build}.",
    "-- Commit: {commit}",
    "-- Do not edit: regenerate instead.",
)

#: The files `render_types` produces, in the order they are written.
TYPES_FILES: tuple[str, ...] = (
    "api.lua",
    "events.lua",
    "enums.lua",
    "structures.lua",
    "constants.lua",
    "objects.lua",
    "host.lua",
)

#: `column_width` from `stylua.toml`; no generated line may exceed it.
STYLUA_COLUMN_WIDTH = 100

#: Documentation lines are wrapped a little short of the StyLua width so that
#: a prefix (`---`) and an indentation level inside an enum table still fit.
DOC_COLUMN_WIDTH = 96

#: The comment marker every documentation and annotation line starts with.
DOC_PREFIX = "---"

#: Words Lua reserves; a parameter or field spelled like one is renamed.
LUA_KEYWORDS = frozenset(
    "and break do else elseif end false for function goto if in local nil not or repeat "
    "return then true until while".split()
)

#: The LuaCATS type written when a name resolves to nothing. Validation refuses
#: metadata with an unknown type, so this is a last line of defence, not a path
#: the generator expects to take.
UNKNOWN_TYPE = "any"

#: The Lua table Blizzard publishes its enumerations under.
ENUM_TABLE = "Enum"

#: The Lua table Blizzard publishes its constants tables under.
CONSTANTS_TABLE = "Constants"


class TypesRenderError(ValueError):
    """The metadata cannot be rendered as definition files."""


class _Writer:
    """Accumulates the lines of one file.

    Lines are collected and joined once at the end; string concatenation in a
    loop over a Retail-sized flavour would be quadratic.
    """

    def __init__(self, header: Sequence[str]) -> None:
        self._lines: list[str] = list(header)

    def line(self, text: str = "") -> None:
        self._lines.append(text)

    def blank(self) -> None:
        """Separate two declarations; never doubles a blank line."""
        if self._lines and self._lines[-1] != "":
            self._lines.append("")

    def doc(self, paragraphs: Iterable[str], indent: str = "") -> None:
        """Write documentation paragraphs as wrapped `---` lines."""
        for paragraph in paragraphs:
            for wrapped in wrap_documentation(paragraph, indent):
                self._lines.append(wrapped)

    def text(self) -> str:
        return "\n".join(self._lines) + "\n"


def wrap_documentation(paragraph: str, indent: str = "") -> list[str]:
    """Split one paragraph into `---` lines no longer than `DOC_COLUMN_WIDTH`.

    A paragraph that already contains line breaks keeps them: the tables use
    them for lists. Nothing is escaped; a comment cannot terminate early in Lua.
    """
    width = DOC_COLUMN_WIDTH - len(indent) - len(DOC_PREFIX)
    lines: list[str] = []
    for source_line in paragraph.splitlines() or [""]:
        wrapped = textwrap.wrap(
            source_line, width=width, break_long_words=False, break_on_hyphens=False
        ) or [""]
        lines.extend(f"{indent}{DOC_PREFIX}{text}" for text in wrapped)
    return lines


def header_lines(provenance: model.Provenance) -> list[str]:
    """`GENERATED_HEADER_LINES` filled in from the flavour's provenance."""
    values = {
        "flavour": provenance.flavour,
        "repository": provenance.repository,
        "commit": provenance.commit,
        "version": provenance.version or "unknown",
        "build": provenance.build if provenance.build is not None else "unknown",
    }
    return [line.format(**values) for line in GENERATED_HEADER_LINES]


def lua_identifier(name: str) -> str:
    """The name as a Lua identifier: a reserved word gets a trailing underscore."""
    if name in LUA_KEYWORDS:
        return f"{name}_"
    return name


def defined_lua_types(metadata: model.FlavourMetadata) -> set[str]:
    """The type names this flavour defines, spelled as LuaCATS writes them.

    Structures, callbacks and object types keep their names; an enumeration
    is `Enum.<Name>`, because that is the table the client publishes it under
    and the name `lua_type` renders. Keeping the Lua spelling in the set lets
    `lua_type` tell an enum from a structure with one lookup.
    """
    defined = {f"{ENUM_TABLE}.{enum.name}" for enum in metadata.enums}
    defined.update(structure.name for structure in metadata.structures)
    defined.update(callback.name for callback in metadata.callbacks)
    for namespace in metadata.namespaces:
        class_name = namespace.object_class_name
        if class_name is not None:
            defined.add(class_name)
    return defined


def _resolve_type_name(name: str, host_types: model.HostTypes, defined: set[str]) -> str:
    """The LuaCATS spelling of one type name (no table shape, no nilability)."""
    enum_name = f"{ENUM_TABLE}.{name}"
    if enum_name in defined:
        return enum_name
    if name in defined:
        return name
    host_type = host_types.types.get(name)
    if host_type is None:
        return UNKNOWN_TYPE
    if host_type.kind == "class":
        return host_type.name
    if host_type.kind == "opaque":
        return UNKNOWN_TYPE
    return host_type.lua


def _optional(type_expression: str) -> str:
    """Mark a type expression nilable; a union is bracketed so `?` covers all of it."""
    if "|" in type_expression:
        return f"({type_expression})?"
    return f"{type_expression}?"


def lua_type(parameter: model.Parameter, host_types: model.HostTypes, defined: set[str]) -> str:
    """The LuaCATS type expression for a parameter.

    A host type is spelled as `types.json` says: a `class` kind renders as its
    own name, `alias` and `primitive` as their `lua` field, `opaque` as `any`.
    An enumeration the flavour defines renders as `Enum.<Name>`; a structure,
    callback or object type as its name. A `table` with an inner type is an
    array `<Inner>[]`, and with a key type too a map `table<Key, Inner>`. A
    nilable parameter appends `?`. An unknown name renders `any`: validation
    already refused unknown names, so this is only a last line of defence.
    """
    if parameter.type == "table" and parameter.inner_type is not None:
        inner = _resolve_type_name(parameter.inner_type, host_types, defined)
        if parameter.key_type is not None:
            key = _resolve_type_name(parameter.key_type, host_types, defined)
            expression = f"table<{key}, {inner}>"
        else:
            expression = f"{inner}[]"
    else:
        expression = _resolve_type_name(parameter.type, host_types, defined)
    if parameter.nilable:
        return _optional(expression)
    return expression


class _TypeContext:
    """What every file needs to spell a type: the host table and the flavour's names."""

    def __init__(self, metadata: model.FlavourMetadata, host_types: model.HostTypes) -> None:
        self.host_types = host_types
        self.defined = defined_lua_types(metadata)

    def type_of(self, parameter: model.Parameter) -> str:
        return lua_type(parameter, self.host_types, self.defined)

    def optional_type_of(self, parameter: model.Parameter) -> str:
        """The type with `?` whether or not the parameter itself says nilable."""
        return self.type_of(dataclasses.replace(parameter, nilable=True))

    def bare_type_of(self, parameter: model.Parameter) -> str:
        """The type without `?`, for places where `?` is written on the name instead."""
        return self.type_of(dataclasses.replace(parameter, nilable=False))


def _namespace_path_segments(flavour: flavours.Flavour) -> list[str]:
    """`wow.classic.era.api` -> `["wow", "classic", "era", "api"]`."""
    return flavour.namespace.split(".")


def _wrapped_namespaces(metadata: model.FlavourMetadata) -> list[model.Namespace]:
    """The namespaces that become tables under `api`, by wrapper name."""
    namespaces = [namespace for namespace in metadata.namespaces if namespace.kind != "object"]
    return sorted(namespaces, key=lambda namespace: namespace.wrapper)


def _object_namespaces(metadata: model.FlavourMetadata) -> list[model.Namespace]:
    """The script object types, by their type name (the documentation system)."""
    namespaces = [namespace for namespace in metadata.namespaces if namespace.kind == "object"]
    return sorted(namespaces, key=lambda namespace: namespace.system)


def _require_identifier(name: str, where: str) -> str:
    """A name used with dot syntax in generated code must be a plain identifier.

    Wrapper names are lowerCamelCase by the naming rules, so only a Blizzard
    name that lowerCamelCases to a reserved word (`C_End` -> `end`) can fail
    here; the fix is an exception in `naming.json`, not a rename by this
    module, because the runtime file must use the same name.
    """
    if name in LUA_KEYWORDS:
        raise TypesRenderError(f"{where}: {name!r} is a Lua reserved word; add a naming exception")
    return name


def _restrictions_text(function: model.Function) -> str | None:
    """A `Restrictions:` doc paragraph naming the markers the function carries, or nothing."""
    markers: list[str] = []
    if function.has_restrictions:
        markers.append("hasRestrictions")
    if function.is_protected:
        markers.append("isProtected")
    if function.secret_arguments is not None:
        markers.append(f"secretArguments={function.secret_arguments}")
    markers.extend(function.flags)
    if not markers:
        return None
    return f"Restrictions: {', '.join(markers)}"


def function_stub_lines(qualified_name: str, parameters: Sequence[str]) -> list[str]:
    """`function <name>(<params>) end`, broken the way StyLua breaks a long one.

    StyLua keeps the stub on one line while the whole line, `end` included,
    fits in `STYLUA_COLUMN_WIDTH`; past that it puts every parameter on its
    own line and closes with `)` and `end` on lines of their own. Writing the
    same shape here keeps the formatter a check instead of a step.
    """
    one_line = f"function {qualified_name}({', '.join(parameters)}) end"
    if len(one_line) <= STYLUA_COLUMN_WIDTH:
        return [one_line]
    lines = [f"function {qualified_name}("]
    for position, parameter in enumerate(parameters):
        separator = "," if position < len(parameters) - 1 else ""
        lines.append(f"    {parameter}{separator}")
    lines.extend([")", "end"])
    return lines


def _write_function_annotations(
    writer: _Writer, function: model.Function, context: _TypeContext
) -> list[str]:
    """Write the doc, `@param` and `@return` lines of a function; return its parameter names."""
    writer.doc(function.documentation)
    parameter_names: list[str] = []
    for argument in function.arguments:
        name = lua_identifier(argument.name)
        parameter_names.append(name)
        optional = "?" if argument.nilable or argument.has_default else ""
        writer.line(f"{DOC_PREFIX}@param {name}{optional} {context.bare_type_of(argument)}")
    for value in function.returns:
        if function.may_return_nothing:
            type_expression = context.optional_type_of(value)
        else:
            type_expression = context.type_of(value)
        writer.line(f"{DOC_PREFIX}@return {type_expression} {lua_identifier(value.name)}")
    restrictions = _restrictions_text(function)
    if restrictions is not None:
        writer.doc((restrictions,))
    return parameter_names


def _write_flavour_root(writer: _Writer, flavour: flavours.Flavour) -> None:
    """Declare `wow`, each path segment class and the global, generically from the path."""
    segments = _namespace_path_segments(flavour)
    for depth in range(len(segments) - 1):
        class_name = ".".join(segments[: depth + 1])
        child = segments[depth + 1]
        child_class = ".".join(segments[: depth + 2])
        writer.blank()
        if depth == 0:
            writer.line(f"{DOC_PREFIX}The World of Warcraft API namespaces `apiKit` publishes.")
        writer.line(f"{DOC_PREFIX}@class {class_name}")
        writer.line(f"{DOC_PREFIX}@field {child} {child_class}")
    writer.blank()
    writer.line(f"{DOC_PREFIX}@type {segments[0]}")
    writer.line(f"{segments[0]} = {{}}")


def _write_api_class(
    writer: _Writer, metadata: model.FlavourMetadata, flavour: flavours.Flavour
) -> None:
    """Declare the `<ns>` class: one field per namespace, alias and reserved table."""
    namespace = flavour.namespace
    writer.blank()
    writer.line(
        f"{DOC_PREFIX}The {flavour.display_name} World of Warcraft API: `local api = {namespace}`."
    )
    writer.line(f"{DOC_PREFIX}@class {namespace}")
    for entry in _wrapped_namespaces(metadata):
        writer.line(f"{DOC_PREFIX}@field {entry.wrapper} {namespace}.{entry.wrapper}")
        if entry.alias is not None:
            writer.line(f"{DOC_PREFIX}@field {entry.alias} {namespace}.{entry.wrapper}")
    for reserved in ("events", "enums", "constants"):
        writer.line(f"{DOC_PREFIX}@field {reserved} {namespace}.{reserved}")
    writer.blank()
    writer.line("-- Namespaces are fields of one local table: Lua allows 200 locals per chunk.")
    writer.line("local api = {}")


def _write_namespace_class(
    writer: _Writer, entry: model.Namespace, flavour: flavours.Flavour, context: _TypeContext
) -> None:
    """Declare `<ns>.<wrapper>` and one function stub per documented function."""
    wrapper = _require_identifier(entry.wrapper, f"namespace {entry.system}")
    class_name = f"{flavour.namespace}.{wrapper}"
    writer.blank()
    writer.doc(entry.documentation)
    if entry.blizzard_namespace is not None:
        writer.line(f"{DOC_PREFIX}Wraps `{entry.blizzard_namespace}`.")
    else:
        writer.line(f"{DOC_PREFIX}Wraps the global functions of the `{entry.system}` system.")
    writer.line(f"{DOC_PREFIX}@class {class_name}")
    writer.line(f"api.{wrapper} = {{}}")
    for function in sorted(entry.functions, key=lambda function: function.wrapper):
        function_name = _require_identifier(function.wrapper, f"{wrapper}.{function.name}")
        writer.blank()
        parameters = _write_function_annotations(writer, function, context)
        for line in function_stub_lines(f"api.{wrapper}.{function_name}", parameters):
            writer.line(line)


def _render_api(
    metadata: model.FlavourMetadata, flavour: flavours.Flavour, context: _TypeContext
) -> str:
    writer = _Writer(header_lines(metadata.provenance))
    _write_flavour_root(writer, flavour)
    _write_api_class(writer, metadata, flavour)
    for entry in _wrapped_namespaces(metadata):
        _write_namespace_class(writer, entry, flavour, context)
    return writer.text()


def _payload_signature(payload: Sequence[model.Parameter], context: _TypeContext) -> str:
    """`fun(name: type, other?: type)` for an event's handler arguments."""
    parts = []
    for parameter in payload:
        optional = "?" if parameter.nilable else ""
        type_expression = context.bare_type_of(parameter)
        parts.append(f"{lua_identifier(parameter.name)}{optional}: {type_expression}")
    return f"fun({', '.join(parts)})"


def _render_events(
    metadata: model.FlavourMetadata, flavour: flavours.Flavour, context: _TypeContext
) -> str:
    writer = _Writer(header_lines(metadata.provenance))
    events = sorted(metadata.events, key=lambda event: event.name)
    namespace = flavour.namespace

    writer.blank()
    writer.line(f"{DOC_PREFIX}Event names as string constants: `api.events.playerLogin`.")
    writer.line(f"{DOC_PREFIX}@class {namespace}.events")
    for event in events:
        writer.doc(event.documentation)
        writer.line(f'{DOC_PREFIX}@field {event.wrapper} "{event.literal_name}"')

    writer.blank()
    writer.line(f"{DOC_PREFIX}The handler arguments each event delivers, by event string.")
    writer.line(f"{DOC_PREFIX}@class {namespace}.eventPayloads")
    for event in events:
        writer.doc(event.documentation)
        signature = _payload_signature(event.payload, context)
        writer.line(f"{DOC_PREFIX}@field {event.literal_name} {signature}")
    return writer.text()


def _enum_field_key(name: str) -> str:
    """How a field name is written inside a table constructor."""
    if name in LUA_KEYWORDS or not name.isidentifier():
        return f'["{name}"]'
    return name


def _write_enum_table(writer: _Writer, enum: model.Enum) -> None:
    """`---@enum Enum.<Name>` over `Enum.<Name> = { ... }`, fields in table order."""
    writer.blank()
    writer.doc(enum.documentation)
    writer.line(f"{DOC_PREFIX}@enum {ENUM_TABLE}.{enum.name}")
    if not enum.fields:
        writer.line(f"{ENUM_TABLE}.{enum.name} = {{}}")
        return
    writer.line(f"{ENUM_TABLE}.{enum.name} = {{")
    for field in enum.fields:
        writer.doc(field.documentation, indent="    ")
        writer.line(f"    {_enum_field_key(field.name)} = {field.value},")
    writer.line("}")


def _render_enums(
    metadata: model.FlavourMetadata, flavour: flavours.Flavour, context: _TypeContext
) -> str:
    writer = _Writer(header_lines(metadata.provenance))
    enums = sorted(metadata.enums, key=lambda enum: enum.name)

    writer.blank()
    writer.line(f"{DOC_PREFIX}The enumerations the client publishes.")
    writer.line(f"{DOC_PREFIX}@class {ENUM_TABLE}")
    for enum in enums:
        writer.line(f"{DOC_PREFIX}@field {enum.name} {ENUM_TABLE}.{enum.name}")
    writer.line(f"{ENUM_TABLE} = {{}}")

    for enum in enums:
        _write_enum_table(writer, enum)

    writer.blank()
    writer.line(f"{DOC_PREFIX}Enumerations by wrapper name: `api.enums.<name> == Enum.<Name>`.")
    writer.line(f"{DOC_PREFIX}@class {flavour.namespace}.enums")
    for enum in enums:
        writer.line(f"{DOC_PREFIX}@field {enum.wrapper} {ENUM_TABLE}.{enum.name}")
    return writer.text()


def _write_structure(writer: _Writer, structure: model.Structure, context: _TypeContext) -> None:
    writer.blank()
    writer.doc(structure.documentation)
    writer.line(f"{DOC_PREFIX}@class {structure.name}")
    for field in structure.fields:
        writer.doc(field.documentation)
        optional = "?" if field.nilable else ""
        type_expression = context.bare_type_of(field)
        writer.line(f"{DOC_PREFIX}@field {lua_identifier(field.name)}{optional} {type_expression}")


def _callback_signature(callback: model.Callback, context: _TypeContext) -> str:
    """`fun(args): returns` for a callback; the return part is omitted when there is none."""
    arguments = _payload_signature(callback.arguments, context)
    if not callback.returns:
        return arguments
    returns = ", ".join(context.type_of(value) for value in callback.returns)
    return f"{arguments}: {returns}"


def _render_structures(
    metadata: model.FlavourMetadata, flavour: flavours.Flavour, context: _TypeContext
) -> str:
    writer = _Writer(header_lines(metadata.provenance))
    for structure in sorted(metadata.structures, key=lambda structure: structure.name):
        _write_structure(writer, structure, context)
    for callback in sorted(metadata.callbacks, key=lambda callback: callback.name):
        writer.blank()
        writer.doc(callback.documentation)
        writer.line(f"{DOC_PREFIX}@alias {callback.name} {_callback_signature(callback, context)}")
    return writer.text()


def _constant_type(value: model.ConstantValue, context: _TypeContext) -> str:
    """The type of one constant: its declared type when it resolves, else `any`.

    A constant written as an expression over other tables is left to `any`
    unless its declared type is known; evaluating expressions needs the whole
    flavour and is not this module's job.
    """
    parameter = model.Parameter(name=value.name, type=value.type)
    return context.type_of(parameter)


def _write_constants_table(
    writer: _Writer, table: model.ConstantsTable, context: _TypeContext
) -> None:
    writer.blank()
    writer.doc(table.documentation)
    writer.line(f"{DOC_PREFIX}@class {CONSTANTS_TABLE}.{table.name}")
    for value in table.values:
        writer.doc(value.documentation)
        writer.line(
            f"{DOC_PREFIX}@field {lua_identifier(value.name)} {_constant_type(value, context)}"
        )


def _render_constants(
    metadata: model.FlavourMetadata, flavour: flavours.Flavour, context: _TypeContext
) -> str:
    writer = _Writer(header_lines(metadata.provenance))
    tables = sorted(metadata.constants, key=lambda table: table.name)

    writer.blank()
    writer.line(f"{DOC_PREFIX}The constants tables the client publishes.")
    writer.line(f"{DOC_PREFIX}@class {CONSTANTS_TABLE}")
    for table in tables:
        writer.line(f"{DOC_PREFIX}@field {table.name} {CONSTANTS_TABLE}.{table.name}")
    writer.line(f"{CONSTANTS_TABLE} = {{}}")

    for table in tables:
        _write_constants_table(writer, table, context)

    writer.blank()
    writer.line(f"{DOC_PREFIX}Constants tables by wrapper name: `api.constants.<name>`.")
    writer.line(f"{DOC_PREFIX}@class {flavour.namespace}.constants")
    for table in tables:
        writer.line(f"{DOC_PREFIX}@field {table.wrapper} {CONSTANTS_TABLE}.{table.name}")
    return writer.text()


def _write_object_class(writer: _Writer, entry: model.Namespace, context: _TypeContext) -> None:
    """Declare a script object type; methods use the Blizzard name, called on host objects.

    The class is declared under the name parameters refer to (`AbbreviateConfig`
    for the system `AbbreviateConfigAPI`), so a hover on such a parameter shows
    the methods.
    """
    class_name = _require_identifier(entry.object_class_name or entry.system, f"object {entry.system}")
    writer.blank()
    writer.doc(entry.documentation)
    if entry.object_type is not None:
        writer.line(f"{DOC_PREFIX}A script object of type `{entry.object_type}`.")
    writer.line(f"{DOC_PREFIX}@class {class_name}")
    writer.line(f"local {class_name} = {{}}")
    for function in sorted(entry.functions, key=lambda function: function.name):
        method_name = _require_identifier(function.name, f"{class_name}:{function.name}")
        writer.blank()
        parameters = _write_function_annotations(writer, function, context)
        for line in function_stub_lines(f"{class_name}:{method_name}", parameters):
            writer.line(line)


def _render_objects(
    metadata: model.FlavourMetadata, flavour: flavours.Flavour, context: _TypeContext
) -> str:
    writer = _Writer(header_lines(metadata.provenance))
    for entry in _object_namespaces(metadata):
        _write_object_class(writer, entry, context)
    return writer.text()


def _render_host(
    metadata: model.FlavourMetadata, flavour: flavours.Flavour, context: _TypeContext
) -> str:
    """Aliases and empty classes for the host types; primitives and opaque names need nothing.

    A host class the flavour itself defines as an object type is left to
    `objects.lua`, which declares it with its methods; declaring it twice would
    make the language server report a duplicate class.
    """
    writer = _Writer(header_lines(metadata.provenance))
    defined_here = metadata.defined_type_names()
    for name in context.host_types.names():
        host_type = context.host_types.types[name]
        if host_type.kind == "class" and name in defined_here:
            continue
        if host_type.kind == "alias":
            writer.blank()
            writer.line(f"{DOC_PREFIX}@alias {name} {host_type.lua}")
        elif host_type.kind == "class":
            writer.blank()
            writer.line(f"{DOC_PREFIX}@class {name}")
    return writer.text()


#: Each output file and the function that renders it.
_RENDERERS = {
    "api.lua": _render_api,
    "events.lua": _render_events,
    "enums.lua": _render_enums,
    "structures.lua": _render_structures,
    "constants.lua": _render_constants,
    "objects.lua": _render_objects,
    "host.lua": _render_host,
}


def render_types(
    metadata: model.FlavourMetadata, flavour: flavours.Flavour, host_types: model.HostTypes
) -> dict[str, str]:
    """Render the flavour's definition files as `{relative path: text}`.

    Paths are relative to `packages/apiKit/types/<flavour id>/`. The same
    input always produces the same bytes: every list is sorted here (enum
    fields keep table order, as the client's tables do) and nothing depends on
    the clock or the environment.
    """
    context = _TypeContext(metadata, host_types)
    return {name: _RENDERERS[name](metadata, flavour, context) for name in TYPES_FILES}
