"""Render and read the `.toc` of the standalone MoltenCodes addon.

The framework installs in two ways: embedded in an addon's own `Libs/`, or as an
addon of its own that other addons depend on. The second needs a `.toc`, and
that `.toc` is generated rather than committed, because every line of it is
already recorded elsewhere:

- the `## Interface` numbers come from `tooling/validation/supported_clients.json`;
- the file list is the builder's load order over the release packages;
- the version is the packager's `@project-version@` placeholder, substituted
  from the tag when the addon sites' zip is built.

This module only renders and reads the text. Which packages go in, and in what
order, is decided by `tooling.package.build` (`select_packages` and
`load_order`), so the builder's bundle, the packager's zip and
`python3 -m tooling.release.library_toc` can never disagree. The field
conventions follow `docs/EMBEDDING.md` ("TOC fields and packaging").
"""

from __future__ import annotations

from typing import Sequence


#: The name of the addon that ships every release Kit. The packager's
#: `package-as` in `.pkgmeta` and the builder's `--all` bundle use it too.
FRAMEWORK_ADDON_NAME = "MoltenCodes"

#: `## Author:` of every generated `.toc`.
AUTHOR = "MoltenCodes"

#: The packager replaces this with the tag when it builds a zip.
VERSION_PLACEHOLDER = "@project-version@"

#: The icon shown next to the addon in the in-game addon list.
ICON_TEXTURE = "Interface\\Icons\\INV_Misc_Gear_01"

#: A free-text category for people and addon managers; the sites take theirs
#: from the project page.
CATEGORY = "Libraries"

#: The licence every package manifest declares.
LICENSE_NAME = "MIT"

#: The repository the addon comes from.
WEBSITE = "https://github.com/MoltenCodes/core"

#: What the whole-framework addon is, in one sentence.
FRAMEWORK_NOTES = (
    "The MoltenCodes framework for World of Warcraft addons, installed once so "
    "addons can depend on it instead of embedding it."
)


def addon_name(facade: str | None = None) -> str:
    """Return the addon (and folder, and `.toc`) name of a bundle.

    `None` names the whole framework, `MoltenCodes`. A facade such as
    `TimerKit` names the single-Kit addon `MoltenCodes-TimerKit`; the client
    requires the folder and its `.toc` to carry the same name.
    """
    if facade is None:
        return FRAMEWORK_ADDON_NAME
    return f"{FRAMEWORK_ADDON_NAME}-{facade}"


def addon_notes(facade: str | None = None) -> str:
    """Return the `## Notes:` sentence for the framework or for one Kit's addon."""
    if facade is None:
        return FRAMEWORK_NOTES
    return (
        f"{facade} from the MoltenCodes framework for World of Warcraft addons, installed "
        "once so addons can depend on it instead of embedding it."
    )


def toc_entry(package_id: str, facade_file: str) -> str:
    """Return the `.toc` line that loads one package's facade.

    Paths are relative to the addon folder and use backslashes, as the client
    and every published `.toc` do: `timerKit\\TimerKit.lua`.
    """
    return f"{package_id}\\{facade_file}"


def entry_to_bundle_path(entry: str) -> str:
    """Convert a `.toc` file line to the POSIX path `manifest.json` records."""
    return entry.replace("\\", "/")


def render_toc(
    *,
    name: str,
    notes: str,
    interface_line: str,
    entries: Sequence[str],
) -> str:
    """Return the text of an addon `.toc`.

    `interface_line` is the complete `## Interface: ...` line from the
    supported-client table, `entries` the file lines in load order (see
    `toc_entry`). The file ends with a newline.
    """
    lines = [
        interface_line,
        f"## Title: {name}",
        f"## Notes: {notes}",
        f"## Author: {AUTHOR}",
        f"## Version: {VERSION_PLACEHOLDER}",
        f"## IconTexture: {ICON_TEXTURE}",
        f"## X-Category: {CATEGORY}",
        f"## X-License: {LICENSE_NAME}",
        f"## X-Website: {WEBSITE}",
        "",
        "# Generated by tooling.release.library_toc; see docs/RELEASES.md.",
        "# Registry first, then every Kit after the Kits it depends on.",
        *entries,
    ]
    return "\n".join(lines) + "\n"


def listed_files(text: str) -> list[str]:
    """Return the file lines of a `.toc`, in order.

    The client reads every non-blank line that does not start with `#` as a
    file to load; `##` lines are fields and `#` lines are comments.
    """
    files: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            files.append(stripped)
    return files
