---@meta
---@diagnostic disable: missing-return
-- Generated by `python3 -m tooling.api.generate` from the classic-mop metadata.
-- Source: Gethe/wow-ui-source, client 5.5.4 build 69934.
-- Commit: cde55d0033e89b246381385b2f063cd6c6047ef8
-- Do not edit: regenerate instead.

---@alias AnimationDataEnum string

---@alias ArtifactTiers string

---@class AuraData

---@alias AuraFilters string

---@class AzeriteEmpoweredItemLocation

---@class AzeriteItemLocation

---@alias BigInteger integer

---@alias BigUInteger integer

---@alias BlendMode string

---@class CScriptObject

---@alias CalendarEventID integer

---@class ChatBubbleFrame

---@alias ClickButton string

---@alias ClubId string

---@alias ClubInvitationId string

---@alias ClubMemberOpaqueId string

---@alias ClubStreamId string

---@class ColorMixin

---@alias ConnectionIptype string

---@alias ConnectionProtocol string

---@class CooldownFrame

---@alias CurveType string

---@alias DiscordID string

---@alias DrawLayer string

---@alias DurationMillisecondsPrimitive number

---@alias DurationSeconds number

---@alias DurationSecondsDouble number

---@alias DurationSecondsPrimitive number

---@class DurationTextBinding

---@class EmptiableItemLocation

---@alias EncounterTimelineEventID integer

---@class FileAsset

---@alias FilterMode string

---@alias FontAlphabet string

---@class FontAsset

---@alias FramePoint string

---@class FrameScriptObject

---@alias FrameStrata string

---@alias FrameTime number

---@alias GameMode string

---@alias GameRule string

---@class GarrisonFollower

---@alias HTMLTextType string

---@alias HouseSettingFlags integer

---@alias IDOrLink number|string

---@alias InsertMode string

---@alias InventorySlots integer

---@class ItemCreationContext

---@class ItemInfo

---@class ItemLocation

---@class ItemLocationMixin

---@class ItemTransmogInfo

---@class ItemTransmogInfoMixin

---@alias JustifyHorizontal string

---@alias JustifyVertical string

---@alias KStringDiscordUserName string

---@alias LoopType string

---@class LuaCurveEvaluatedResult

---@class LuaDurationClock

---@alias LuaFunctionReference function

---@alias LuaInventorySlot integer

---@alias LuaValueReference any

---@alias LuaValueVariant any

---@class ModelAsset

---@class ModelSceneFrame

---@class ModelSceneFrameActor

---@alias MouseButton string

---@class NamePlateFrame

---@alias NotificationDbId integer

---@alias Orientation string

---@class PartyPlaylistEntry

---@class PlayerLocation

---@class PlayerLocationMixin

---@alias RecruitAcceptanceID integer

---@class ReportInfo

---@class ReportInfoMixin

---@class RoleShortageReward

---@class ScriptRegion

---@alias ScriptTypeName string

---@alias SendChatMessageType string

---@alias SimpleButtonStateToken string

---@class SimplePathAnim

---@class SimpleVectorGraphics

---@class SimpleWindow

---@alias SingleColorValue number

---@alias SmoothingType string

---@alias SoundHandle integer

---@alias SpellIdentifier number|string

---@alias TBFFlags string

---@class TextureAsset

---@class TextureAssetDisk

---@class Tooltip

---@class TooltipComparisonItem

---@class TooltipData

---@class TransmogLocation

---@class TransmogLocationMixin

---@class UiMapPoint

---@alias UnitToken string

---@alias UnitTokenNamePlate string

---@alias UnitTokenPvPRestrictedForAddOns string

---@alias UnitTokenRestrictedForAddOns string

---@alias UnitTokenVariant string

---@class Vector2DMixin

---@class Vector3DMixin

---@alias WOWGUID string

---@alias WOWMONEY integer

---@alias WeeklyRewardItemDBID integer

---@class colorRGB

---@class colorRGBA

---@alias fileID integer

---@alias kstringAuroraName string

---@alias kstringClubMessage string

---@alias kstringLfgListApplicant string

---@alias kstringLfgListChat string

---@alias kstringLfgListSearch string

---@alias luaIndex integer

---@alias mouseButton string

---@alias normalizedValue number

---@alias size number

---@alias textureAtlas string

---@alias textureKit string

---@alias time_t integer

---@alias uiAddon number|string

---@alias uiFontHeight number

---@class uiRect

---@alias uiUnit number

---@class vector2

---@class vector3
