local Env = require("ClientKitTestEnv")

describe("ClientKit manifest", function()
    before_each(function()
        Env.Reset()
    end)
    after_each(function()
        Env.Reset()
    end)

    it("matches runtime API and revision metadata", function()
        local ClientKit = Env.NewPackage()
        local file = assert(io.open("packages/clientKit/package.manifest.json", "r"))
        local contents = file:read("*a")
        file:close()
        local api = tonumber(contents:match('"api"%s*:%s*(%d+)'))
        local revision = tonumber(contents:match('"revision"%s*:%s*(%d+)'))
        assert.are.equal(ClientKit.API, api)
        assert.are.equal(ClientKit.REVISION, revision)
    end)
end)
