local Env = require("InteropKitTestEnv")

describe("InteropKit manifest", function()
  before_each(function()
    Env.Reset()
  end)
  after_each(function()
    Env.Reset()
  end)

  it("matches runtime API and revision metadata", function()
    local InteropKit = Env.NewPackage()
    local file = assert(io.open("packages/interopKit/package.manifest.json", "r"))
    local contents = file:read("*a")
    file:close()
    local api = tonumber(contents:match('"api"%s*:%s*(%d+)'))
    local revision = tonumber(contents:match('"revision"%s*:%s*(%d+)'))
    assert.are.equal(InteropKit.API, api)
    assert.are.equal(InteropKit.REVISION, revision)
  end)
end)
