local TestEnv = require("LifecycleKitTestEnv")

describe("LifecycleKit", function()
    local LifecycleKit
    before_each(function()
        LifecycleKit = TestEnv.NewPackage()
    end)
    after_each(TestEnv.Reset)

    it("returns one stable instance per addon name", function()
        local first = LifecycleKit:ForAddon("MyAddon")
        local second = LifecycleKit:ForAddon("MyAddon")
        local other = LifecycleKit:ForAddon("OtherAddon")
        assert.are.equal(first, second)
        assert.are_not.equal(first, other)
    end)

    it("starts in loading state", function()
        local life = LifecycleKit:ForAddon("MyAddon")
        assert.are.equal("loading", life:GetState())
        assert.is_false(life:IsLoaded())
        assert.is_false(life:IsReady())
        assert.is_false(life:IsShutdown())
        assert.are.equal("MyAddon", life:GetAddonName())
    end)

    it("ignores ADDON_LOADED for other addons", function()
        local life = LifecycleKit:ForAddon("MyAddon")
        TestEnv.LoadAddon("OtherAddon")
        assert.are.equal("loading", life:GetState())
    end)

    it("moves to loaded for its own ADDON_LOADED", function()
        local life = LifecycleKit:ForAddon("MyAddon")
        TestEnv.LoadAddon("MyAddon")
        assert.are.equal("loaded", life:GetState())
        assert.is_true(life:IsLoaded())
        assert.is_false(life:IsReady())
    end)

    it("moves to ready after login", function()
        local life = LifecycleKit:ForAddon("MyAddon")
        TestEnv.LoadAddon("MyAddon")
        TestEnv.Login()
        assert.are.equal("ready", life:GetState())
        assert.is_true(life:IsLoaded())
        assert.is_true(life:IsReady())
    end)

    it("remembers login that occurs before addon loaded", function()
        local life = LifecycleKit:ForAddon("MyAddon")
        TestEnv.Login()
        assert.are.equal("loading", life:GetState())
        TestEnv.LoadAddon("MyAddon")
        assert.are.equal("ready", life:GetState())
    end)

    it("moves to shutdown on logout", function()
        local life = LifecycleKit:ForAddon("MyAddon")
        TestEnv.LoadAddon("MyAddon")
        TestEnv.Login()
        TestEnv.Logout()
        assert.are.equal("shutdown", life:GetState())
        assert.is_true(life:IsShutdown())
    end)
end)
