local TestEnv = require("TimerKitTestEnv")

describe("TimerKit validation and host failures", function()
    after_each(TestEnv.Reset)

    it("rejects invalid timer definitions", function()
        local TimerKit = TestEnv.NewPackage()

        assert.has_error(function() TimerKit:New(nil) end)
        assert.has_error(function() TimerKit:After(-1, function() end) end)
        assert.has_error(function() TimerKit:Every(0, function() end) end)
        assert.has_error(function() TimerKit:Every(-1, function() end) end)
        assert.has_error(function() TimerKit:After(1, "not a function") end)
        assert.has_error(function()
            TimerKit:New({ delay = 1, callback = function() end, unknown = true })
        end)
    end)

    it("rejects non-finite delays", function()
        local TimerKit = TestEnv.NewPackage()
        assert.has_error(function() TimerKit:After(0 / 0, function() end) end)
        assert.has_error(function() TimerKit:After(math.huge, function() end) end)
    end)

    it("rolls back logical state if native creation fails", function()
        local TimerKit = TestEnv.NewPackage()
        local timer = TimerKit:New({ delay = 1, callback = function() end })
        TestEnv.FailNextCreate("native create failed")

        local ok, value = pcall(function() timer:Start() end)
        assert.is_false(ok)
        assert.are.equal("native create failed", value)
        assert.are.equal("idle", timer:GetState())
        assert.are.equal(0, timer:GetScope():GetActiveCount())

        assert.is_true(timer:Start())
    end)

    it("rolls back if the host returns an invalid native handle", function()
        local TimerKit = TestEnv.NewPackage()
        local timer = TimerKit:New({ delay = 1, callback = function() end })
        TestEnv.ReturnNextNative("invalid-handle")

        local ok, value = pcall(function() timer:Start() end)
        assert.is_false(ok)
        assert.is_true(tostring(value):find("invalid native timer handle", 1, true) ~= nil)
        assert.are.equal("idle", timer:GetState())
        assert.are.equal(0, timer:GetScope():GetActiveCount())

        assert.is_true(timer:Start())
    end)

    it("keeps logical cancellation final if native cancellation errors", function()
        local TimerKit = TestEnv.NewPackage()
        local timer = TimerKit:Every(1, function() end)
        local scope = timer:GetScope()
        TestEnv.FailNextCancel("native cancel failed")

        local ok, value = pcall(function() timer:Cancel() end)
        assert.is_false(ok)
        assert.are.equal("native cancel failed", value)
        assert.are.equal("cancelled", timer:GetState())
        assert.are.equal(0, scope:GetActiveCount())
        TestEnv.InvokeRaw(1)
        assert.are.equal("cancelled", timer:GetState())
    end)

    it("continues scope cleanup after one native cancellation error", function()
        local TimerKit = TestEnv.NewPackage()
        local scope = TimerKit:CreateScope()
        local first = scope:Every(1, function() end)
        local second = scope:Every(1, function() end)
        TestEnv.FailNextCancel("cancel failed")

        local ok, value = pcall(function() scope:CancelAll() end)
        assert.is_false(ok)
        assert.are.equal("cancel failed", value)
        assert.is_true(first:IsCancelled())
        assert.is_true(second:IsCancelled())
        assert.are.equal(0, scope:GetActiveCount())
    end)
end)
