local TestEnv = require("TimerKitTestEnv")

describe("TimerKit addon lifecycle scopes", function()
    after_each(TestEnv.Reset)

    it("returns one scope per addon", function()
        local TimerKit = TestEnv.NewPackage()
        local first = TimerKit:ForAddon("Example")
        local second = TimerKit:ForAddon("Example")
        local other = TimerKit:ForAddon("Other")

        assert.are.equal(first, second)
        assert.are_not.equal(first, other)
        assert.are.equal("Example", first:GetAddonName())
    end)

    it("closes addon scopes on PLAYER_LOGOUT", function()
        local TimerKit = TestEnv.NewPackage()
        local scope = TimerKit:ForAddon("Example")
        local timer = scope:Every(1, function() end)

        TestEnv.Logout()
        assert.is_true(scope:IsClosed())
        assert.is_true(timer:IsCancelled())
        assert.are.equal(0, scope:GetActiveCount())
    end)

    it("keeps manual scopes independent from addon shutdown", function()
        local TimerKit = TestEnv.NewPackage()
        local scope = TimerKit:CreateScope()
        local timer = scope:Every(1, function() end)

        TestEnv.Logout()
        assert.is_false(scope:IsClosed())
        assert.is_true(timer:IsPending())
    end)

    it("returns an already-closed scope when its lifecycle already shut down", function()
        local TimerKit, _, _, _, LifecycleKit = TestEnv.NewPackage()
        LifecycleKit:ForAddon("Late")
        TestEnv.Logout()

        local scope = TimerKit:ForAddon("Late")
        assert.is_true(scope:IsClosed())
        assert.has_error(function()
            scope:After(1, function() end)
        end)
    end)

    it("isolates addon-owned scopes", function()
        local TimerKit = TestEnv.NewPackage()
        local first = TimerKit:ForAddon("First")
        local second = TimerKit:ForAddon("Second")
        first:After(1, function() end)
        local secondTimer = second:After(1, function() end)

        first:Close()
        assert.is_true(first:IsClosed())
        assert.is_false(second:IsClosed())
        assert.is_true(secondTimer:IsPending())
    end)
end)
