local TestEnv = require("TimerKitTestEnv")

describe("TimerKit scopes", function()
  after_each(TestEnv.Reset)

  it("tracks only active timers", function()
    local TimerKit = TestEnv.NewPackage()
    local scope = TimerKit:CreateScope()
    local idle = scope:New({ delay = 2, callback = function() end })
    local running = scope:After(1, function() end)

    assert.are.equal(1, scope:GetActiveCount())
    idle:Start()
    assert.are.equal(2, scope:GetActiveCount())
    TestEnv.FireNative(1)
    assert.are.equal(1, scope:GetActiveCount())
    running:Cancel()
    assert.are.equal(1, scope:GetActiveCount())
    idle:Cancel()
    assert.are.equal(0, scope:GetActiveCount())
  end)

  it("cancels all active timers without closing the scope", function()
    local TimerKit = TestEnv.NewPackage()
    local scope = TimerKit:CreateScope()
    local first = scope:After(1, function() end)
    local second = scope:Every(2, function() end)

    assert.are.equal(2, scope:CancelAll())
    assert.is_true(first:IsCancelled())
    assert.is_true(second:IsCancelled())
    assert.is_false(scope:IsClosed())
    assert.are.equal(0, scope:GetActiveCount())

    local replacement = scope:After(1, function() end)
    assert.is_true(replacement:IsPending())
  end)

  it("counts only timers that were still running when bulk cancellation began", function()
    local TimerKit = TestEnv.NewPackage()
    local scope = TimerKit:CreateScope()
    local running = scope:Every(1, function() end)
    local idle = scope:New({ delay = 1, callback = function() end })
    local completed = scope:After(1, function() end)
    TestEnv.FireNative(2)

    assert.are.equal("completed", completed:GetState())
    assert.are.equal(1, scope:CancelAll())
    assert.is_true(running:IsCancelled())
    assert.are.equal("idle", idle:GetState())
    assert.are.equal(0, scope:CancelAll())
  end)

  it("closes terminally and rejects future timer creation", function()
    local TimerKit = TestEnv.NewPackage()
    local scope = TimerKit:CreateScope()
    local timer = scope:After(1, function() end)

    assert.is_true(scope:Close())
    assert.is_true(scope:IsClosed())
    assert.is_true(timer:IsCancelled())
    assert.is_false(scope:Close())
    assert.has_error(function()
      scope:After(1, function() end)
    end)
    assert.has_error(function()
      timer:Restart()
    end)
  end)

  it("recovers package-level convenience methods after their internal scope is closed", function()
    local TimerKit = TestEnv.NewPackage()
    local first = TimerKit:After(1, function() end)
    local oldScope = first:GetScope()
    oldScope:Close()

    local second = TimerKit:After(1, function() end)
    assert.are_not.equal(oldScope, second:GetScope())
    assert.is_true(second:IsPending())
  end)
end)
