local TestEnv = require("CacheKitTestEnv")

describe("CacheKit TTL cache", function()
  local CacheKit
  before_each(function()
    CacheKit = TestEnv.NewPackage()
  end)
  after_each(TestEnv.Reset)

  it("expires an entry once ttlSeconds have passed since it was set", function()
    local cache = CacheKit:NewTtl({ maxEntries = 4, ttlSeconds = 5 })
    cache:Set("a", 1)

    TestEnv.AdvanceMs(4999)
    assert.are.equal(1, cache:Get("a"))

    TestEnv.AdvanceMs(1)
    assert.is_nil(cache:Get("a"))
    assert.are.equal(0, cache:GetCount())

    local stats = cache:GetStats()
    assert.are.equal(1, stats.hits)
    assert.are.equal(1, stats.misses)
    assert.are.equal(0, stats.evictions)
  end)

  it("does not extend an entry's age when it is read", function()
    local cache = CacheKit:NewTtl({ maxEntries = 4, ttlSeconds = 2 })
    cache:Set("a", 1)
    TestEnv.AdvanceMs(1500)
    assert.are.equal(1, cache:Get("a"))
    TestEnv.AdvanceMs(500)
    assert.is_nil(cache:Get("a"))
  end)

  it("restarts an entry's age when it is set again", function()
    local cache = CacheKit:NewTtl({ maxEntries = 4, ttlSeconds = 2 })
    cache:Set("a", 1)
    TestEnv.AdvanceMs(1500)
    cache:Set("a", 2)
    TestEnv.AdvanceMs(1500)
    assert.are.equal(2, cache:Get("a"))
  end)

  it("reports an expired entry as absent through Peek without removing it", function()
    local cache = CacheKit:NewTtl({ maxEntries = 4, ttlSeconds = 1 })
    cache:Set("a", 1)
    TestEnv.AdvanceMs(1000)
    assert.is_nil(cache:Peek("a"))
    assert.are.equal(1, cache:GetCount())
    assert.is_true(cache:Delete("a"))
  end)

  it("still evicts the least recently used entry when full", function()
    local cache = CacheKit:NewTtl({ maxEntries = 2, ttlSeconds = 60 })
    cache:Set("a", 1)
    cache:Set("b", 2)
    cache:Get("a")
    cache:Set("c", 3)
    assert.is_nil(cache:Peek("b"))
    assert.are.equal(1, cache:Peek("a"))
    assert.are.equal(1, cache:GetStats().evictions)
  end)

  it("does not count dropping an expired entry to make room as an eviction", function()
    local cache = CacheKit:NewTtl({ maxEntries = 1, ttlSeconds = 1 })
    cache:Set("a", 1)
    TestEnv.AdvanceMs(1000)
    cache:Set("b", 2)
    assert.are.equal(0, cache:GetStats().evictions)
    assert.are.equal(2, cache:Get("b"))
  end)

  it("never expires entries on a host without GetTimePreciseSec", function()
    local ClocklessCacheKit = TestEnv.NewPackageWithoutClock()
    local cache = ClocklessCacheKit:NewTtl({ maxEntries = 2, ttlSeconds = 1 })
    cache:Set("a", 1)
    TestEnv.AdvanceMs(60000)
    assert.are.equal(1, cache:Get("a"))

    cache:Set("b", 2)
    cache:Set("c", 3)
    assert.is_nil(cache:Peek("a"))
  end)
end)
