local TestEnv = require("MediaKitTestEnv")

describe("MediaKit:Fetch, Has and IsFileDataID", function()
    local MediaKit
    before_each(function()
        MediaKit = TestEnv.NewPackage()
    end)
    after_each(TestEnv.Reset)

    it("returns nil and false for a name nobody registered", function()
        assert.is_nil(MediaKit:Fetch("statusbar", "Nobody"))
        assert.is_false(MediaKit:Has("statusbar", "Nobody"))
    end)

    it("answers Has exactly when Fetch returns data", function()
        MediaKit:Register("border", "Pack Border", "Interface\\Pack\\Border")
        assert.is_true(MediaKit:Has("border", "Pack Border"))
        assert.are.equal("Interface\\Pack\\Border", MediaKit:Fetch("border", "Pack Border"))
        assert.is_false(MediaKit:Has("statusbar", "Pack Border"))
    end)

    it("is case-sensitive, like the names a player picks from a list", function()
        MediaKit:Register("statusbar", "Smooth", "Interface\\Pack\\Smooth")
        assert.is_nil(MediaKit:Fetch("statusbar", "smooth"))
    end)

    it("refuses unknown types, bad names and bad options at the caller", function()
        TestEnv.expectErrorContaining("MediaKit:Fetch type must be one of", function()
            MediaKit:Fetch("fonts", "Name")
        end)
        TestEnv.expectErrorContaining("MediaKit:Has name must be a non-empty string", function()
            MediaKit:Has("font", nil)
        end)
        TestEnv.expectErrorContaining("MediaKit:Fetch options must be a table", function()
            MediaKit:Fetch("font", "Name", true)
        end)
        TestEnv.expectErrorContaining("MediaKit:Fetch anyScript must be a boolean", function()
            MediaKit:Fetch("font", "Name", { anyScript = 1 })
        end)
        TestEnv.expectErrorContaining(
            'MediaKit:Has options contains unknown field "any"',
            function()
                MediaKit:Has("font", "Name", { any = true })
            end
        )
    end)

    it("recognises FileDataIDs as finite positive integers", function()
        assert.is_true(MediaKit:IsFileDataID(1))
        assert.is_true(MediaKit:IsFileDataID(554003))
        assert.is_true(MediaKit:IsFileDataID(2 ^ 40))
        assert.is_false(MediaKit:IsFileDataID(0))
        assert.is_false(MediaKit:IsFileDataID(-1))
        assert.is_false(MediaKit:IsFileDataID(2.5))
        assert.is_false(MediaKit:IsFileDataID(math.huge))
        assert.is_false(MediaKit:IsFileDataID(0 / 0))
        assert.is_false(MediaKit:IsFileDataID("554003"))
        assert.is_false(MediaKit:IsFileDataID(nil))
    end)
end)
