local TestEnv = require("WidgetKitTestEnv")

describe("WidgetKit bootstrap", function()
    after_each(TestEnv.Reset)

    it("returns the same facade on duplicate embedded load and keeps live widgets", function()
        local WidgetKit = TestEnv.NewPackage()
        local label = WidgetKit:Create("Label")
        local reloaded = TestEnv.ReloadPackage()
        assert.are.equal(WidgetKit, reloaded)
        assert.is_true(WidgetKit:IsWidget(label))
        assert.are.equal(1, WidgetKit:GetTypeVersion("Label"))
        WidgetKit:Release(label)
    end)

    it("publishes through Registry with its bounds", function()
        local WidgetKit, Registry = TestEnv.NewPackage()
        local registered, revision = Registry:Get("widgetKit", 1)
        assert.are.equal(WidgetKit, registered)
        assert.are.equal(WidgetKit.REVISION, revision)
        assert.are.equal(256, WidgetKit.MAX_CREATED)
        assert.are.equal(256, WidgetKit.MAX_CHILDREN)
        assert.are.equal(16, WidgetKit.MAX_CALLBACKS)
    end)

    it("requires Registry, PoolKit and SignalKit", function()
        TestEnv.Reset()
        TestEnv.InstallWowApi()
        local ok, failure = pcall(require, "WidgetKit")
        assert.is_false(ok)
        assert.is_true(tostring(failure):find("requires Registry API 2", 1, true) ~= nil)

        TestEnv.Reset()
        TestEnv.InstallWowApi()
        require("Registry")
        require("SignalKit")
        ok, failure = pcall(TestEnv.requireAfterFailedLoad, "WidgetKit")
        assert.is_false(ok)
        assert.is_true(tostring(failure):find("requires PoolKit API 1", 1, true) ~= nil)

        TestEnv.Reset()
        TestEnv.InstallWowApi()
        require("Registry")
        require("PoolKit")
        ok, failure = pcall(TestEnv.requireAfterFailedLoad, "WidgetKit")
        assert.is_false(ok)
        assert.is_true(tostring(failure):find("requires SignalKit API 1", 1, true) ~= nil)
    end)

    it("refuses an incomplete facade left by an earlier failed load", function()
        TestEnv.Reset()
        TestEnv.InstallWowApi()
        local Registry = require("Registry")
        require("SignalKit")
        require("PoolKit")
        Registry:Register("widgetKit", 1, 1)
        local ok, failure = pcall(TestEnv.requireAfterFailedLoad, "WidgetKit")
        assert.is_false(ok)
        assert.is_true(tostring(failure):find("MoltenCodes WidgetKit", 1, true) ~= nil)
    end)

    it("does not reinterpret private state owned by a newer compatible revision", function()
        local WidgetKit, Registry = TestEnv.NewPackage()
        local upgraded, previous = Registry:Register("widgetKit", 1, 99)
        assert.are.equal(WidgetKit, upgraded)
        assert.are.equal(WidgetKit.REVISION, previous)
        rawset(WidgetKit, "REVISION", 99)
        rawset(WidgetKit, "_state", { schema = 999 })
        package.loaded["WidgetKit"] = nil
        local reloaded = require("WidgetKit")
        assert.are.equal(WidgetKit, reloaded)
        assert.are.equal(99, reloaded.REVISION)
    end)

    it("upgrades in place: prototypes, types, live widgets and layouts carry over", function()
        local WidgetKit = TestEnv.NewPackage()
        local widgetBase = WidgetKit.Widget
        local containerBase = WidgetKit.Container
        local window = WidgetKit:Create("Frame")
        local group = WidgetKit:Create("Group")
        group:SetFullWidth(true)
        local label = WidgetKit:Create("Label")
        label:SetText("kept")
        group:AddChild(label)
        window:AddChild(group)
        local pooled = WidgetKit:Create("Button")
        WidgetKit:Release(pooled)

        local nextRevision = WidgetKit.REVISION + 1
        local upgraded = TestEnv.LoadRevision(nextRevision)
        assert.are.equal(WidgetKit, upgraded)
        assert.are.equal(nextRevision, upgraded.REVISION)
        assert.are.equal(widgetBase, upgraded.Widget)
        assert.are.equal(containerBase, upgraded.Container)
        assert.are.equal(1, upgraded:GetTypeVersion("Label"))

        -- Live widgets keep working under the new copy's methods.
        label:SetText("still here")
        assert.is_true(window:PerformLayout())
        assert.are.equal(label, group:GetChildren()[1])
        -- Same base versions: the pooled widget is reused.
        assert.are.equal(pooled, upgraded:Create("Button"))
        upgraded:Release(window)
        assert.is_false(upgraded:IsWidget(label))
    end)

    it("upgrades a revision 1 copy in place with its widgets, types and limits", function()
        TestEnv.Reset()
        TestEnv.InstallWowApi()
        TestEnv.InstallScreen()
        for _, name in ipairs({ "Registry", "SignalKit", "PoolKit", "SchemaKit", "OptionsKit" }) do
            require(name)
        end
        local old = TestEnv.LoadRevision(1)
        local group = old:Create("Group") ---@cast group -nil
        local label = old:Create("Label") ---@cast label -nil
        group:AddChild(label)
        label:SetUserData("kept", true)
        old:SetLimits({ maxDropdownEntries = old.UNBOUNDED })

        local upgraded = require("WidgetKit")
        assert.are.equal(old, upgraded)
        assert.is_true(upgraded.REVISION > 1)
        assert.is_true(upgraded:IsWidget(label))
        assert.are.equal(label, group:GetChildren()[1])
        assert.is_true(label:GetUserData("kept"))
        assert.are.equal(old.UNBOUNDED, upgraded:GetLimits().maxDropdownEntries)
        assert.are.equal(1, upgraded:GetTypeVersion("Label"))
        -- The widgets revision 1 built run the current methods at once.
        TestEnv.InstallSecretProbe()
        local secret = TestEnv.NewSecret()
        local ok, failure = pcall(label.SetJustifyH, label, secret)
        assert.is_false(ok)
        assert.is_truthy(
            tostring(failure):find("SetJustifyH justify must not be a secret value", 1, true)
        )
        upgraded:Release(group)
        assert.is_false(upgraded:IsWidget(label))
    end)

    it("discards pooled base widgets when a newer copy raises their version", function()
        local WidgetKit = TestEnv.NewPackage()
        local pooled = WidgetKit:Create("Label")
        local borrowed = WidgetKit:Create("Label")
        WidgetKit:Release(pooled)

        TestEnv.LoadRevision(WidgetKit.REVISION + 1, { ["    Label = 1,"] = "    Label = 2," })
        assert.are.equal(2, WidgetKit:GetTypeVersion("Label"))
        local fresh = WidgetKit:Create("Label")
        assert.are_not.equal(pooled, fresh)
        WidgetKit:Release(borrowed)
        assert.are_not.equal(borrowed, WidgetKit:Create("Label"))
    end)
end)
