local TestEnv = require("WidgetKitTestEnv")

describe("WidgetKit widget base", function()
    local WidgetKit
    before_each(function()
        WidgetKit = TestEnv.NewPackage()
        TestEnv.TakeReportedErrors()
    end)
    after_each(TestEnv.Reset)

    it("installs the shared base prototype on every widget", function()
        local label = WidgetKit:Create("Label")
        local group = WidgetKit:Create("Group")
        assert.are.equal(WidgetKit.Widget.SetCallback, label.SetCallback)
        assert.are.equal(WidgetKit.Container.AddChild, group.AddChild)
        assert.are.equal(WidgetKit.Widget.SetUserData, group.SetUserData)
        assert.is_nil(label.AddChild)
        assert.are.equal(label.frame, label:GetFrame())
    end)

    it("fires a named callback with the widget, the name and the arguments", function()
        local label = WidgetKit:Create("Label")
        local seen = nil
        label:SetCallback("OnThing", function(widget, name, ...)
            seen = { widget = widget, name = name, count = select("#", ...), first = ... }
        end)
        assert.is_true(label:Fire("OnThing", 1, nil, 3))
        assert.are.equal(label, seen.widget)
        assert.are.equal("OnThing", seen.name)
        assert.are.equal(3, seen.count)
        assert.are.equal(1, seen.first)
        assert.is_false(label:Fire("OnOther"))

        label:SetCallback("OnThing", nil)
        assert.is_false(label:Fire("OnThing"))
    end)

    it("isolates and reports a callback error", function()
        local label = WidgetKit:Create("Label")
        label:SetCallback("OnThing", function()
            error("callback bug", 0)
        end)
        assert.is_false(label:Fire("OnThing"))
        local reported = TestEnv.TakeReportedErrors()
        assert.are.equal(1, #reported)
        assert.are.equal("callback bug", reported[1].value)
    end)

    it("caps named callbacks at sixteen per widget", function()
        local label = WidgetKit:Create("Label")
        for index = 1, WidgetKit.MAX_CALLBACKS do
            label:SetCallback("C" .. index, function() end)
        end
        -- Replacing an existing name never counts against the cap.
        label:SetCallback("C1", function() end)
        TestEnv.expectErrorContaining("at most 16 callbacks", function()
            label:SetCallback("C17", function() end)
        end)
        label:SetCallback("C2", nil)
        label:SetCallback("C17", function() end)
    end)

    it("keeps user data per widget", function()
        local first = WidgetKit:Create("Label")
        local second = WidgetKit:Create("Label")
        first:SetUserData("path", "a.b")
        assert.are.equal("a.b", first:GetUserData("path"))
        assert.is_nil(second:GetUserData("path"))
        first:SetUserData("path", nil)
        assert.is_nil(first:GetUserData("path"))
        TestEnv.expectErrorContaining("key must not be nil", function()
            first:SetUserData(nil, 1)
        end)
    end)

    it("records size requests and passes size, anchors and visibility through", function()
        local label = WidgetKit:Create("Label")
        label:SetWidth(120)
        label:SetHeight(30)
        assert.are.equal(120, label:GetWidth())
        assert.are.equal(30, label:GetHeight())
        label:SetRelativeWidth(0.5)
        assert.are.equal(0.5, label:GetRelativeWidth())
        label:SetFullWidth(true)
        assert.is_true(label:IsFullWidth())
        assert.is_nil(label:GetRelativeWidth())
        label:SetFullHeight(true)
        assert.is_true(label:IsFullHeight())
        TestEnv.expectErrorContaining("above 0 and at most 1", function()
            label:SetRelativeWidth(1.5)
        end)

        label:SetPoint("TOPLEFT", 5, -6)
        local point, _, relativePoint, x, y = label:GetPoint(1)
        assert.are.same({ "TOPLEFT", "TOPLEFT", 5, -6 }, { point, relativePoint, x, y })
        assert.are.equal(1, label:GetNumPoints())
        label:ClearAllPoints()
        assert.are.equal(0, label:GetNumPoints())

        label:Hide()
        assert.is_false(label:IsShown())
        label:Show()
        assert.is_true(label:IsShown())
        assert.is_true(label:IsVisible())
    end)

    it("re-parents a free widget to a frame or a widget, never one inside a container", function()
        local window = WidgetKit:Create("Frame")
        local label = WidgetKit:Create("Label")
        label:SetParent(window)
        assert.are.equal(window.content, label.frame:GetParent())
        local plain = TestEnv.GetGlobal("CreateFrame")("Frame")
        label:SetParent(plain)
        assert.are.equal(plain, label.frame:GetParent())

        local group = WidgetKit:Create("Group")
        group:AddChild(label)
        TestEnv.expectErrorContaining("inside a container", function()
            label:SetParent(plain)
        end)
    end)

    it("keeps one focused widget and tells the previous one it lost focus", function()
        local first = WidgetKit:Create("EditBox")
        local second = WidgetKit:Create("EditBox")
        first:SetFocus()
        assert.is_true(first.singleBox:HasFocus())
        second:SetFocus()
        assert.are.equal(second, WidgetKit:GetFocus())
        assert.is_false(first.singleBox:HasFocus())
        assert.is_true(WidgetKit:ClearFocus())
        assert.is_false(second.singleBox:HasFocus())
        assert.is_false(WidgetKit:ClearFocus())
        assert.is_nil(WidgetKit:GetFocus())
    end)
end)
