---@meta
---@diagnostic disable: missing-return
-- Generated by `python3 -m tooling.api.generate` from the ptr metadata.
-- Source: Gethe/wow-ui-source, client 12.1.5 build 69952.
-- Commit: 5c9363cc1b4e80b98963e3fcc87ab460fa911a94
-- Do not edit: regenerate instead.

---The constants tables the client publishes.
---@class Constants
---@field AuctionConstants Constants.AuctionConstants
---@field CAAConstants Constants.CAAConstants
---@field CalendarGetEventTypeConstants Constants.CalendarGetEventTypeConstants
---@field Callings Constants.Callings
---@field CatalogShopVirtualCurrencyConstants Constants.CatalogShopVirtualCurrencyConstants
---@field CharCustomizationConstants Constants.CharCustomizationConstants
---@field ChatFrameConstants Constants.ChatFrameConstants
---@field CombatLogMessageLimits Constants.CombatLogMessageLimits
---@field CombatLogObjectMasks Constants.CombatLogObjectMasks
---@field CombatLogObjectTargetMasks Constants.CombatLogObjectTargetMasks
---@field ContentTrackingConsts Constants.ContentTrackingConsts
---@field CooldownFrameDefaults Constants.CooldownFrameDefaults
---@field CooldownViewerUIConstants Constants.CooldownViewerUIConstants
---@field CraftingOrderConsts Constants.CraftingOrderConsts
---@field CurrencyConsts Constants.CurrencyConsts
---@field DelvesConsts Constants.DelvesConsts
---@field EditModeConsts Constants.EditModeConsts
---@field EditModeLayoutConsts Constants.EditModeLayoutConsts
---@field EncodingLimits Constants.EncodingLimits
---@field EncounterTimelineEventConstants Constants.EncounterTimelineEventConstants
---@field EncounterTimelineIconMasks Constants.EncounterTimelineIconMasks
---@field EventScheduler Constants.EventScheduler
---@field GroupBuffUIConstants Constants.GroupBuffUIConstants
---@field HousingCatalogConsts Constants.HousingCatalogConsts
---@field HousingConsts Constants.HousingConsts
---@field ITEM_WEAPON_SUBCLASSConstants Constants.ITEM_WEAPON_SUBCLASSConstants
---@field ITEM_WEAPON_SUBCLASSConstants_PostMists Constants.ITEM_WEAPON_SUBCLASSConstants_PostMists
---@field InventoryConstants Constants.InventoryConstants
---@field ItemConsts Constants.ItemConsts
---@field ItemConsts_Mainline Constants.ItemConsts_Mainline
---@field LFGConstsExposed Constants.LFGConstsExposed
---@field LFG_ROLEConstants Constants.LFG_ROLEConstants
---@field LevelConstsExposed Constants.LevelConstsExposed
---@field LootConsts Constants.LootConsts
---@field LossOfControlConsts Constants.LossOfControlConsts
---@field MacroConsts Constants.MacroConsts
---@field MajorFactionsConsts Constants.MajorFactionsConsts
---@field MoneyFormattingConstants Constants.MoneyFormattingConstants
---@field MountDynamicFlightConsts Constants.MountDynamicFlightConsts
---@field PartyCountdownConstants Constants.PartyCountdownConstants
---@field PetConsts Constants.PetConsts
---@field PetConsts_PostCata Constants.PetConsts_PostCata
---@field ProfessionConsts Constants.ProfessionConsts
---@field PvpInfoConsts Constants.PvpInfoConsts
---@field QuestWatchConsts Constants.QuestWatchConsts
---@field RecentAlliesConsts Constants.RecentAlliesConsts
---@field SpellBookSpellIDs Constants.SpellBookSpellIDs
---@field SpellCooldownConsts Constants.SpellCooldownConsts
---@field TTSConstants Constants.TTSConstants
---@field TalentConsts Constants.TalentConsts
---@field TalentTierConstants Constants.TalentTierConstants
---@field TieredEntranceConsts Constants.TieredEntranceConsts
---@field TimerunningConsts Constants.TimerunningConsts
---@field TraitConsts Constants.TraitConsts
---@field Transmog Constants.Transmog
---@field TransmogOutfitDataConsts Constants.TransmogOutfitDataConsts
---@field UICharacterClasses Constants.UICharacterClasses
---@field UnitAuraUIConstants Constants.UnitAuraUIConstants
---@field UnitEventConstants Constants.UnitEventConstants
---@field UnitPowerSpellIDs Constants.UnitPowerSpellIDs
Constants = {}

---@class Constants.AuctionConstants
---@field DEFAULT_AUCTION_PRICE_MULTIPLIER number

---@class Constants.CAAConstants
---@field CAAEnabledDefault boolean
---@field CAAVoiceDefault number
---@field CAASayCombatStartDefault boolean
---@field CAASayCombatEndDefault boolean
---@field CAAPlayerHealthPercentDefault number
---@field CAAPlayerHealthFormatDefault number
---@field CAAPulsePlayerHealthPercentDefault number
---@field CAATargetNameDefault boolean
---@field CAATargetHealthPercentDefault number
---@field CAATargetHealthFormatDefault number
---@field CAATargetDeathBehaviorDefault number
---@field CAASayIfTargetedDefault number
---@field CAAPartyHealthPercentDefault number
---@field CAAPlayerCastModeDefault number
---@field CAAPlayerCastFormatDefault number
---@field CAATargetCastModeDefault number
---@field CAATargetCastFormatDefault number
---@field CAAInterruptCastDefault number
---@field CAAInterruptCastSuccessDefault number
---@field CAASayYourDebuffsDefault boolean
---@field CAASayYourDebuffsFormatDefault number
---@field CAASayYourDebuffsMinDurationDefault number
---@field CAASayYourDebuffsMinDurationMin number
---@field CAASayYourDebuffsMinDurationMax number
---@field CAASayYourDebuffsMinDurationStep number
---@field CAADebuffSelfAlertDefault number
---@field CAAPlayerResourcePercentDefault number
---@field CAAPlayerResourceFormatDefault number
---@field CAAMinCastTimeMin number
---@field CAAMinCastTimeMax number
---@field CAAMinCastTimeDefault number
---@field CAAMinCastTimeStep number
---@field CAAThrottleMin number
---@field CAAThrottleMax number
---@field CAAThrottleDefault number
---@field CAAThrottleStep number
---@field CAAFrequencyMin number
---@field CAAFrequencyMax number
---@field CAAFrequencyDefault number
---@field CAASampleTextThrottleTime number
---@field CAASamePercentThrottleTime number

---@class Constants.CalendarGetEventTypeConstants
---@field DEFAULT_CALENDAR_GET_EVENT_TYPE Enum.CalendarGetEventType

---@class Constants.Callings
---@field MaxCallings number

---@class Constants.CatalogShopVirtualCurrencyConstants
---@field HEARTHSTEEL_VC_CURRENCY_CODE string
---@field TRADERS_TENDER_VC_CURRENCY_CODE string

---@class Constants.CharCustomizationConstants
---@field CHAR_CUSTOMIZE_CUSTOM_DISPLAY_OPTION_FIRST Enum.CharCustomizationType
---@field CHAR_CUSTOMIZE_CUSTOM_DISPLAY_OPTION_LAST Enum.CharCustomizationType
---@field NUM_CUSTOM_DISPLAY number
---@field NAME_RESERVATION_DAYS number

---@class Constants.ChatFrameConstants
---@field MaxChatWindows number
---@field MaxChatChannels number
---@field MaxCharacterNameBytes number

---@class Constants.CombatLogMessageLimits
---@field CombatLogDefaultMessageLimit number
---@field CombatLogMaximumMessageLimit number

---@class Constants.CombatLogObjectMasks
---@field COMBATLOG_OBJECT_AFFILIATION_MASK Enum.CombatLogObject
---@field COMBATLOG_OBJECT_REACTION_MASK Enum.CombatLogObject
---@field COMBATLOG_OBJECT_CONTROL_MASK Enum.CombatLogObject
---@field COMBATLOG_OBJECT_TYPE_MASK Enum.CombatLogObject
---@field COMBATLOG_OBJECT_SPECIAL_MASK Enum.CombatLogObject

---@class Constants.CombatLogObjectTargetMasks
---@field COMBATLOG_OBJECT_RAID_TARGET_MASK Enum.CombatLogObjectTarget
---@field COMBATLOG_OBJECT_RAID_MASK Enum.CombatLogObjectTarget

---@class Constants.ContentTrackingConsts
---@field MaxTrackedCollectableSources number
---@field MaxTrackedAchievements number

---@class Constants.CooldownFrameDefaults
---@field COOLDOWN_DEFAULT_COUNTDOWN_ABBREV_THRESHOLD_MS number
---@field COOLDOWN_DEFAULT_COUNTDOWN_MILLISECOND_THRESHOLD_MS number
---@field COOLDOWN_DEFAULT_COUNTDOWN_MINIMUM_DURATION_MS number
---@field COOLDOWN_DEFAULT_BLING_DURATION_MS number
---@field COOLDOWN_DEFAULT_USE_AURA_DISPLAY_TIME boolean

---@class Constants.CooldownViewerUIConstants
---@field COOLDOWN_VIEWER_LINKED_SPELLS_SIZE number
---@field COOLDOWN_VIEWER_CATEGORY_SET_SIZE number
---@field COOLDOWN_VIEWER_SPEC_AGNOSTIC_PARENT_ID number
---@field COOLDOWN_VIEWER_COMBAT_POTION_ICON_FID number
---@field COOLDOWN_VIEWER_HEALTH_POTION_ICON_FID number
---@field COOLDOWN_VIEWER_HEALTHSTONE_ICON_FID number

---@class Constants.CraftingOrderConsts
---@field MAX_CRAFTING_ORDER_FAVORITE_RECIPES number
---@field NPC_CRAFTING_ORDER_NUM_SUPPORTED_REWARDS number

---@class Constants.CurrencyConsts
---@field PLAYER_CURRENCY_CLIENT_FLAGS Enum.PlayerCurrencyFlagsDbFlags
---@field MAX_CURRENCY_QUANTITY number
---@field CONQUEST_ARENA_AND_BG_META_CURRENCY_ID number
---@field CONQUEST_RATED_BG_META_CURRENCY_ID number
---@field CONQUEST_ASHRAN_META_CURRENCY_ID number
---@field ACCOUNT_WIDE_HONOR_CURRENCY_ID number
---@field ACCOUNT_WIDE_HONOR_LEVEL_CURRENCY_ID number
---@field CONQUEST_CURRENCY_ID number
---@field CONQUEST_POINTS_CURRENCY_ID number
---@field CONQUEST_ARENA_META_CURRENCY_ID number
---@field CONQUEST_BG_META_CURRENCY_ID number
---@field HONOR_CURRENCY_ID number
---@field ARTIFACT_KNOWLEDGE_CURRENCY_ID number
---@field WAR_RESOURCES_CURRENCY_ID number
---@field ECHOES_OF_NYALOTHA_CURRENCY_ID number
---@field DRAGON_ISLES_SUPPLIES_CURRENCY_ID number
---@field QUESTIONMARK_INV_ICON number
---@field PVP_CURRENCY_CONQUEST_ALLIANCE_INV_ICON number
---@field PVP_CURRENCY_CONQUEST_HORDE_INV_ICON number
---@field PVP_CURRENCY_HONOR_ALLIANCE_INV_ICON number
---@field PVP_CURRENCY_HONOR_HORDE_INV_ICON number
---@field CURRENCY_ID_RENOWN number
---@field CURRENCY_ID_RENOWN_KYRIAN number
---@field CURRENCY_ID_RENOWN_VENTHYR number
---@field CURRENCY_ID_RENOWN_NIGHT_FAE number
---@field CURRENCY_ID_RENOWN_NECROLORD number
---@field CURRENCY_ID_WILLING_SOUL number
---@field CURRENCY_ID_RESERVOIR_ANIMA number
---@field CURRENCY_ID_PERKS_PROGRAM_DISPLAY_INFO number
---@field IMMEDIATE_CURRENCY_WALLET_ITEM_ID number
---@field CURRENCY_WALLET_TYPE_WOWMONEY number

---@class Constants.DelvesConsts
---@field DELVES_MIN_PLAYER_LEVEL_CONTENT_TUNING_ID number
---@field DELVES_NORMAL_KEY_CURRENCY_ID number
---@field DELVES_COMPANION_INFO_SELECTION_CHARACTER_DATA_ELEMENT_ID number
---@field DELVES_COMPANION_TOOLTIP_WIDGET_SET_ID number
---@field DELVES_COMPANION_BRANN_CREATURE_ID number
---@field DELVES_COMPANION_VALEERA_CREATURE_ID number

---@class Constants.EditModeConsts
---@field EditModeDefaultGridSpacing number
---@field EditModeMinGridSpacing number
---@field EditModeMaxGridSpacing number
---@field EditModeMaxLayoutsPerType number

---@class Constants.EditModeLayoutConsts
---@field EditModeDefaultLayout Enum.EditModePresetLayouts

---@class Constants.EncodingLimits
---@field EncodingDecompressSizeLimit number
---@field EncodingStackSizeLimit number

---@class Constants.EncounterTimelineEventConstants
---Constant used for invalid event IDs. Script APIs are guaranteed to always return nil data if
---supplied this ID, and events will never be added to the timeline with this ID.
---@field ENCOUNTER_TIMELINE_INVALID_EVENT number
---Minimum size of internal arrays that are preallocated for event storage.
---@field ENCOUNTER_TIMELINE_RESERVED_EVENT_COUNT number

---@class Constants.EncounterTimelineIconMasks
---@field EncounterTimelineTankAlertIcons Enum.EncounterEventIconmask
---@field EncounterTimelineHealerAlertIcons Enum.EncounterEventIconmask
---@field EncounterTimelineDamageAlertIcons Enum.EncounterEventIconmask
---@field EncounterTimelineDeadlyIcons Enum.EncounterEventIconmask
---@field EncounterTimelineDispelIcons Enum.EncounterEventIconmask
---@field EncounterTimelineEnrageIcons Enum.EncounterEventIconmask
---@field EncounterTimelineAllIcons Enum.EncounterEventIconmask
---@field EncounterTimelineRoleIcons Enum.EncounterEventIconmask
---@field EncounterTimelineOtherIcons Enum.EncounterEventIconmask
---@field EncounterTimelineNoIcons Enum.EncounterEventIconmask

---@class Constants.EventScheduler
---@field SCHEDULED_EVENT_REMINDER_WARNING_SECONDS number
---@field SCHEDULED_EVENT_FUTURE_LIMIT number
---@field SCHEDULED_EVENT_REMINDER_DEAD_SECONDS number
---@field SCHEDULED_EVENT_PAST_LIMIT_SECONDS number

---@class Constants.GroupBuffUIConstants
---@field GROUP_BUFF_ITEM_LIST_SIZE number

---@class Constants.HousingCatalogConsts
---@field HOUSING_CATALOG_FEATURED_CATEGORY_ID number
---@field HOUSING_CATALOG_ALL_CATEGORY_ID number
---@field HOUSING_CATALOG_DECOR_MODELSCENEID_DEFAULT number

---@class Constants.HousingConsts
---@field NeighborhoodNameMaxCharacters number
---@field NeighborhoodNameMinCharacters number
---@field BlueprintNameMaxCharacters number
---@field BlueprintNameMinCharacters number
---@field HOUSING_BLUEPRINTS_MAX_PER_BNET_ACCOUNT number
---@field HOUSING_BLUEPRINTS_MAX_BACKUPS_PER_BNET_ACCOUNT number

---@class Constants.ITEM_WEAPON_SUBCLASSConstants
---@field ITEM_WEAPON_SUBCLASS_NONE Enum.ItemWeaponSubclass
---@field ITEM_WEAPON_SUBCLASS_MASK number
---@field ITEM_WEAPON_SUBCLASS_IS2HWEAPON_MASK number
---@field ITEM_WEAPON_SUBCLASS_USES2HANDS_MASK number
---@field ITEM_WEAPON_SUBCLASS_ISRANGEDWEAPON_MASK number
---@field ITEM_WEAPON_SUBCLASS_ISTWOHANDEDRANGEDWEAPON_MASK number
---@field ITEM_WEAPON_SUBCLASS_ISMAINHANDWEAPON_NONRANGED_MASK number

---@class Constants.ITEM_WEAPON_SUBCLASSConstants_PostMists
---@field ITEM_WEAPON_SUBCLASS_ISTITANSGRIPWEAPON_MASK number

---@class Constants.InventoryConstants
---@field NumBagSlots number
---@field NumCharacterBankSlots number
---@field NumReagentBagSlots number
---@field NumAccountBankSlots number
---@field MAX_TRANSACTION_BANK_TABS number

---@class Constants.ItemConsts
---@field NUM_ITEM_ENCHANTMENT_SOCKETS number
---@field MAX_LOOT_OBJECT_ITEMS number
---@field INVALID_BANK_TAB_SLOT number
---@field DEFAULT_ITEM_SAVE_VERSION number
---@field CURRENT_ITEM_SAVE_VERSION number
---@field DEFAULT_ARTIFACT_POWERS_VERSION number
---@field CURRENT_ARTIFACT_POWERS_VERSION number
---@field DEFAULT_RETENTION number

---@class Constants.ItemConsts_Mainline
---@field HWM_SQUISH_ERA_PLAYER_DATA_ACCOUNT_ELEMENT_ID number

---@class Constants.LFGConstsExposed
---@field GROUP_FINDER_MAX_ACTIVITY_CAPACITY number

---@class Constants.LFG_ROLEConstants
---@field LFG_ROLE_NO_ROLE Enum.LFGRole
---@field LFG_ROLE_ANY Enum.LFGRole

---@class Constants.LevelConstsExposed
---@field MIN_RES_SICKNESS_LEVEL number
---@field MIN_ACHIEVEMENT_LEVEL number

---@class Constants.LootConsts
---@field MasterLootQualityThreshold number

---@class Constants.LossOfControlConsts
---@field LOSS_OF_CONTROL_ACTIVE_INDEX number

---@class Constants.MacroConsts
---@field MAX_ACCOUNT_MACROS number
---@field MAX_CHARACTER_MACROS number

---@class Constants.MajorFactionsConsts
---@field WORLD_STATE_RENOWN_CAP_10_0 number
---@field WORLD_STATE_RAPID_RENOWN_CAP_10_0 number
---@field PLUNDERSTORM_MAJOR_FACTION_ID number

---@class Constants.MoneyFormattingConstants
---@field GOLD_REWARD_THRESHOLD_TO_HIDE_COPPER number

---@class Constants.MountDynamicFlightConsts
---@field TRAIT_SYSTEM_ID number
---@field TREE_ID number

---@class Constants.PartyCountdownConstants
---@field MaxCountdownSeconds number

---@class Constants.PetConsts
---@field PETNUMBER_INVALIDSLOT number
---@field MAX_SUMMONABLE_PETS number
---@field PETNUMBER_INVALIDPET number
---@field PETNUMBER_PENDINGPET number

---@class Constants.PetConsts_PostCata
---@field NUM_PET_SLOTS_THAT_NEED_LEARNED_SPELL number
---@field MAX_SUMMONABLE_HUNTER_PETS number
---@field MAX_STABLE_SLOTS number
---@field EXTRA_PET_STABLE_SLOT number
---@field STABLED_PETS_FIRST_SLOT_INDEX number
---@field NUM_PET_SLOTS_HUNTER number
---@field NUM_PET_SLOTS_DEATHKNIGHT number
---@field DEATHKNIGHT_PET_CREATURE_ID number
---@field NUM_PET_SLOTS_MAGE number
---@field NUM_PET_SLOTS_WARLOCK number
---@field MAX_NUM_PET_SLOTS number
---@field PET_MAX_LEVEL_DIFFERENCE number

---@class Constants.ProfessionConsts
---@field NUM_PRIMARY_PROFESSIONS number
---@field CLASSIC_PROFESSION_PARENT_TIER_INDEX number
---@field RUNEFORGING_SKILL_LINE_ID number
---@field RUNEFORGING_ROOT_CATEGORY_ID number
---@field MAX_CRAFTING_REAGENT_SLOTS number
---@field CRAFTING_ORDER_CLAIM_DURATION number
---@field PUBLIC_CRAFTING_ORDER_STALE_THRESHOLD number
---@field CRAFTING_ORDER_ITEM_RETENTION number
---@field CRAFTING_ORDER_CURRENCY_WALLET_ITEM_ID number

---@class Constants.PvpInfoConsts
---@field MaxPlayersPerInstance number
---@field MAX_PVP_LOCK_LIST_MAP number

---@class Constants.QuestWatchConsts
---@field MAX_QUEST_WATCHES number
---@field MAX_WORLD_QUEST_WATCHES_AUTOMATIC number
---@field MAX_WORLD_QUEST_WATCHES_MANUAL number

---@class Constants.RecentAlliesConsts
---@field PIN_EXPIRATION_WARNING_DAYS number

---@class Constants.SpellBookSpellIDs
---@field SPELL_ID_DISMISS_PET number

---@class Constants.SpellCooldownConsts
---@field GLOBAL_RECOVERY_CATEGORY number
---@field COMBAT_POTION_CATEGORY number
---@field HEALTH_POTION_CATEGORY number
---@field HEALTHSTONE_CATEGORY number

---@class Constants.TTSConstants
---@field TTSRateMin number
---@field TTSRateMax number
---@field TTSRateDefault number
---@field TTSVolumeMin number
---@field TTSVolumeMax number
---@field TTSVolumeDefault number

---@class Constants.TalentConsts
---@field NumTalentColumns number

---@class Constants.TalentTierConstants
---@field MAX_TALENT_TIERS number

---@class Constants.TieredEntranceConsts
---@field TIERED_ENTRANCE_TIER_SCORE_VALUE_TIER_LEVEL number
---@field TIERED_ENTRANCE_TIER_SCORE_VALUE_MAP_ID number
---@field TIERED_ENTRANCE_TIER_SCORE_VALUE_PLAYER_CONDITION_ID number
---@field TIERED_ENTRANCE_INFO_WORLD_TIER_DIFFICULTY_CHARACTER_ELEMENT_ID number

---@class Constants.TimerunningConsts
---@field TIMERUNNING_SEASON_NONE number
---@field TIMERUNNING_SEASON_PANDARIA number
---@field TIMERUNNING_SEASON_LEGION number
---@field TIMERUNNING_ITEM_CTR number
---@field TIMERUNNING_LEGION_ARTIFACT_CTR number

---@class Constants.TraitConsts
---@field MAX_COMBAT_TRAIT_CONFIGS number
---@field COMMIT_COMBAT_TRAIT_CONFIG_CHANGES_SPELL_ID number
---@field INSPECT_TRAIT_CONFIG_ID number
---@field STARTER_BUILD_TRAIT_CONFIG_ID number
---@field VIEW_TRAIT_CONFIG_ID number

---@class Constants.Transmog
---@field NoTransmogID number
---@field MainHandTransmogIsIndividualWeapon number
---@field MainHandTransmogIsPairedWeapon number

---@class Constants.TransmogOutfitDataConsts
---@field EQUIP_TRANSMOG_OUTFIT_MANUAL_SPELL_ID number
---@field TRANSMOG_OUTFIT_SLOT_NONE Enum.TransmogOutfitSlot

---@class Constants.UICharacterClasses
---@field Warrior number
---@field Paladin number
---@field Hunter number
---@field Rogue number
---@field Priest number
---@field DeathKnight number
---@field Shaman number
---@field Mage number
---@field Warlock number
---@field Monk number
---@field Druid number
---@field DemonHunter number
---@field Evoker number

---@class Constants.UnitAuraUIConstants
---@field HIDDEN_GROUP_BUFF_LIST_SIZE number
---@field GROUP_BUFF_VISUAL_ALERT_LIST_SIZE number

---@class Constants.UnitEventConstants
---@field MAX_UNIT_TOKENS_IN_EVENT number

---@class Constants.UnitPowerSpellIDs
---@field VOID_METAMORPHOSIS_SPELL_ID number
---@field DARK_HEART_SPELL_ID number
---@field SILENCE_THE_WHISPERS_SPELL_ID number
---@field COLLAPSING_STAR_PASSIVE_SPELL_ID number
---@field COLLAPSING_STAR_SPELL_ID number

---Constants tables by wrapper name: `api.constants.<name>`.
---@class wow.ptr.api.constants
---@field auctionConstants Constants.AuctionConstants
---@field caaConstants Constants.CAAConstants
---@field calendarGetEventTypeConstants Constants.CalendarGetEventTypeConstants
---@field callings Constants.Callings
---@field catalogShopVirtualCurrencyConstants Constants.CatalogShopVirtualCurrencyConstants
---@field charCustomizationConstants Constants.CharCustomizationConstants
---@field chatFrameConstants Constants.ChatFrameConstants
---@field combatLogMessageLimits Constants.CombatLogMessageLimits
---@field combatLogObjectMasks Constants.CombatLogObjectMasks
---@field combatLogObjectTargetMasks Constants.CombatLogObjectTargetMasks
---@field contentTrackingConsts Constants.ContentTrackingConsts
---@field cooldownFrameDefaults Constants.CooldownFrameDefaults
---@field cooldownViewerUIConstants Constants.CooldownViewerUIConstants
---@field craftingOrderConsts Constants.CraftingOrderConsts
---@field currencyConsts Constants.CurrencyConsts
---@field delvesConsts Constants.DelvesConsts
---@field editModeConsts Constants.EditModeConsts
---@field editModeLayoutConsts Constants.EditModeLayoutConsts
---@field encodingLimits Constants.EncodingLimits
---@field encounterTimelineEventConstants Constants.EncounterTimelineEventConstants
---@field encounterTimelineIconMasks Constants.EncounterTimelineIconMasks
---@field eventScheduler Constants.EventScheduler
---@field groupBuffUIConstants Constants.GroupBuffUIConstants
---@field housingCatalogConsts Constants.HousingCatalogConsts
---@field housingConsts Constants.HousingConsts
---@field itemWeaponSubclassConstants Constants.ITEM_WEAPON_SUBCLASSConstants
---@field itemWeaponSubclassConstantsPostMists Constants.ITEM_WEAPON_SUBCLASSConstants_PostMists
---@field inventoryConstants Constants.InventoryConstants
---@field itemConsts Constants.ItemConsts
---@field itemConstsMainline Constants.ItemConsts_Mainline
---@field lfgConstsExposed Constants.LFGConstsExposed
---@field lfgRoleConstants Constants.LFG_ROLEConstants
---@field levelConstsExposed Constants.LevelConstsExposed
---@field lootConsts Constants.LootConsts
---@field lossOfControlConsts Constants.LossOfControlConsts
---@field macroConsts Constants.MacroConsts
---@field majorFactionsConsts Constants.MajorFactionsConsts
---@field moneyFormattingConstants Constants.MoneyFormattingConstants
---@field mountDynamicFlightConsts Constants.MountDynamicFlightConsts
---@field partyCountdownConstants Constants.PartyCountdownConstants
---@field petConsts Constants.PetConsts
---@field petConstsPostCata Constants.PetConsts_PostCata
---@field professionConsts Constants.ProfessionConsts
---@field pvpInfoConsts Constants.PvpInfoConsts
---@field questWatchConsts Constants.QuestWatchConsts
---@field recentAlliesConsts Constants.RecentAlliesConsts
---@field spellBookSpellIDs Constants.SpellBookSpellIDs
---@field spellCooldownConsts Constants.SpellCooldownConsts
---@field ttsConstants Constants.TTSConstants
---@field talentConsts Constants.TalentConsts
---@field talentTierConstants Constants.TalentTierConstants
---@field tieredEntranceConsts Constants.TieredEntranceConsts
---@field timerunningConsts Constants.TimerunningConsts
---@field traitConsts Constants.TraitConsts
---@field transmog Constants.Transmog
---@field transmogOutfitDataConsts Constants.TransmogOutfitDataConsts
---@field uiCharacterClasses Constants.UICharacterClasses
---@field unitAuraUIConstants Constants.UnitAuraUIConstants
---@field unitEventConstants Constants.UnitEventConstants
---@field unitPowerSpellIDs Constants.UnitPowerSpellIDs
